### ISSUE TITLE
Support for multiple architectures/operating systems.

### ISSUE THREAD

**Issue by jmalloc** [Justintime50/homebrew-releaser#14]
Hi there,

I'd love to be able to use `homebrew-releaser` to replace a hacky bash script I wrote that publishes [this formula here](https://github.com/jmalloc/homebrew-grit/blob/master/grit.rb). Is there any way to do this with this action?

If not, is it a feature you might consider adding?

Thanks!

**Comment by Justintime50** [comment]
Hey @jmalloc,

Certainly! This is something I've been meaning to do for awhile now and was previously requested in #9. Getting this right (and automating it) is kind of tricky; though, I'll start looking into this again. I can't promise an ETA but I hope now that even more are requesting it I can get it out in the near future.

**Comment by jmalloc** [comment]
That's great, thanks.  I've subscribed to #9, so feel free to close this.
Ping me any time if I can help out, even if it's just to give some fast feedback.

**Comment by Justintime50** [comment]
Closing in favor of #9, will continue the convo there.

**Comment by Justintime50** [comment]
This has been released! Additional details can be found over on issue #9
