### ISSUE TITLE
Setting `update_readme_table: true` crashes action

### ISSUE THREAD

**Issue by tnahs** [Justintime50/homebrew-releaser#18]
Setting `update_readme_table: true` causes a crash. The test repo did have a `README.md` file.

```plaintext
2022-09-12 07:14:35,037 - DEBUG - checksum.txt written successfully.
2022-09-12 07:14:35,037 - INFO - Generating Homebrew formula for test-readstor...
2022-09-12 07:14:35,038 - INFO - Homebrew formula generated successfully!
2022-09-12 07:14:35,038 - DEBUG - # typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class TestReadstor < Formula
  desc "This?"
  homepage "https://github.com/tnahs/test-readstor"
  url "https://github.com/tnahs/test-readstor/archive/0.1.9.tar.gz"
  sha256 "06b4f595e2ca548034cbb00e6b0177eb06e0c97633b64d50068fd0d173515afc"
  license "MIT"

  def install
    bin.install "test-readstor"
  end
end

2022-09-12 07:14:35,038 - DEBUG - test-homebrew-formulas/formula/test-readstor.rb written successfully.
There was a problem opening or reading the formula data: local variable 'final_name' referenced before assignment
2022-09-12 07:14:35,038 - INFO - Attempting to update the README's project table...
```

Thanks! 😄

**Comment by Justintime50** [comment]
Huh... this one gives me pause. Essentially this one fails because the action can't find the line `class TestReadstor < Formula` but as we can see from the debug output above, this lines exists. I'll push up a patch to set a default empty string; however, I'd be very interested to know if the generated README output on your project produces an empty cell value. If so, please let me know and I'll take another look! Based on what I'm finding, it shouldn't...

**Comment by Justintime50** [comment]
Fixed via https://github.com/Justintime50/homebrew-releaser/commit/7ef2a1c553d04655bb9cd40563a63fcf869cd980

**Comment by tnahs** [comment]
Thanks! 🎉 I'll test it out

**Comment by tnahs** [comment]
Oh! something odd has happened... Action didn't crash but.... 

```markdown
| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
#| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
 | Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
t| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
e| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
s| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
t| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
-| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
h| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
o| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
m| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
e| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
b| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
r| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
e| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
w| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
-| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
f| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
o| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
r| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
m| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
u| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
l| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
a| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
s| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
```

| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
#| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
 | Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
t| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
e| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
s| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
t| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
-| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
h| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
o| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
m| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
e| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
b| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
r| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
e| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
w| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
-| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
f| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
o| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
r| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
m| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
u| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
l| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
a| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |
s| Project                                                 | Description | Install                      |
| ------------------------------------------------------- | ----------- | ---------------------------- |
| [test-readstor](https://github.com/tnahs/test-readstor) | This?       | `brew install test-readstor` |

Repo: https://github.com/tnahs/homebrew-test-formulas

**Comment by Justintime50** [comment]
Heh lovely... mind opening a new issue and link to the action run that did this? I'll have to investigate this one a bit.

**Comment by tnahs** [comment]
Done! Thanks for the quick replies!
