### ISSUE TITLE
What is the recommended way to uncompress assets with the formula's install command?

### ISSUE THREAD

**Issue by leoaugustov** [Justintime50/homebrew-releaser#20]
As the action demands the release asset to be a `tar.gz` file, how is it expected or recommended to uncompress the file with a one-line formula's install command?

I am not familiar with Ruby code and after some googling, I only found multi-line solutions. Also, I have no experience publishing to Homebrew so forgive me if I am missing some crucial detail.

**Comment by Justintime50** [comment]
Hey @leoaugustov, Homebrew will automatically uncompress the archive for you during installation. The instructions you specify in the `install` step will take the uncompressed archive at its root level. You can see some examples of my personal Homebrew formulas: https://github.com/Justintime50/homebrew-formulas/tree/main/formula. You'll notice that for many of these I'm simply moving a binary from say the `src` directory of the archive and putting it into `bin` which is the default behavior for Homebrew.

There are a bunch of resources out there on the subject. One potential option to look at is something like this: https://medium.com/prodopsio/creating-homebrew-taps-for-private-internal-tools-c41363d58ab0. This GitHub Action specifically allows one to automate releasing to a personal Homebrew tap and not to the main Homebrew archive. If that is your aim you'll need to check elsewhere. 

Hopefully the couple links here is a good starting place for you. Let me know if you have other questions about this GitHub Actions specifically.
