### ISSUE TITLE
Get an [Errno 21] Is a directory error when run

### ISSUE THREAD

**Issue by FollowTheProcess** [Justintime50/homebrew-releaser#25]
Hey there!

I'm attempting to build a pipeline for Rust binaries that closely mimics what [GoReleaser](https://goreleaser.com/intro/) does for Go:
- Cross compile on different platforms
- Upload release binaries to GitHub release
- Publish the release

And the reason I'm here: Build the homebrew formula and upload to a personal tap

On this last step I keep hitting a weird error and I wonder if I'm doing something wrong or there is a bug etc.

So I'm working in a [test repo](https://github.com/FollowTheProcess/brewtest) to build the pipeline. I've got everything sorted other than the homebrew thing.

I've got the action configured like [this](https://github.com/FollowTheProcess/brewtest/blob/1cfac17def724169904d0c69635df62a9cc64234/.github/workflows/CI.yml#L132) which as far I can tell is all fine?

But when the action runs I get a `[Errno 21] Is a directory: 'brewtest-0.0.17-darwin-amd64.tar.gz'` as follows:

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/62767721/220176442-9cdc425f-2152-4446-b7ad-1d054634b089.png">

Link to the workflow run: https://github.com/FollowTheProcess/brewtest/actions/runs/4226016232/jobs/7339054900

**Comment by Justintime50** [comment]
Thanks for the well documented issue! I agree that this is probably a bug, though it's a bit odd as the logic used to get the latest archives from a release and those that were attached are near identical. I'll look into this over the next couple days and hopefully have a fix out soon. I briefly skimmed the code and believe I know where this is failing.

**Comment by FollowTheProcess** [comment]
Let me know if there's anything I can do to help 👍🏻

**Comment by Justintime50** [comment]
So I was able to re-run your workflows locally and oddly didn't get your same error, but did get another one. I got `[Errno 2] No such file or directory: 'homebrew-tap/./brewtest.rb'` instead. I think you may be running into this issue because you are storing your formula files at the root of the repo instead of inside a folder which is what Homebrew recommends.

Are you able to test this by moving the formula to a directory in the homebrew tap repo and updating the `formula_folder` variable to match? Let me know if that fixes the problem!

**Comment by FollowTheProcess** [comment]
Ahh okay so it has to be in a subfolder? I assumed from the way GoReleaser does it that it's fine to be in the repo root. I'll try again with that when I get chance 👍🏻 

> Are you able to re-run the failed release job to ensure it wasn't a fluke by chance?
I tried a few times and got the same error unfortunately,  don't think it's a fluke :(

**Comment by Justintime50** [comment]
Homebrew itself can work from the root of a project, though this GitHub Action assumes it's in a subfolder. I could investigate allowing root dirs down the line. If you'd like, feel free to submit a separate issue for that and I can see about adding support.

How interesting. I'll continue investigating. Another debugging step would be to try what I did and run this action locally with the Dockerfile and `docker-compose.yml` file in the repo. This would narrow down the problem to being a GitHub action thing or not if you can also get it to generate correctly locally.

**Comment by FollowTheProcess** [comment]
> Are you able to test this by moving the formula to a directory in the homebrew tap repo and updating the formula_folder variable to match? Let me know if that fixes the problem!

I did this on [this run](https://github.com/FollowTheProcess/brewtest/actions/runs/4266182428/jobs/7426440590) but got the same error (sort of expected I guess)

I'll try running locally and see where I get

**Comment by Justintime50** [comment]
Hey there, do you mind trying again via GitHub Actions? I just pushed an overhaul to how release assets are downloaded and wonder if those changes will magically fix this issue here. This is either v1 or v0.16.0 you can use.

Let me know what happens!

**Comment by FollowTheProcess** [comment]
Success! (I think) https://github.com/FollowTheProcess/brewtest/actions/runs/4332733069/jobs/7565434480

Think it only failed because there is no subdir `Formula` in my brew tap at the moment. I'll make that and take the skip commit off and see what happens

**Comment by FollowTheProcess** [comment]
Well I'd say that works: https://github.com/FollowTheProcess/homebrew-tap/blob/main/Formula/brewtest.rb

Thanks so much for the help! 🎉

**Comment by Justintime50** [comment]
Fantastic! So glad we were able to work this out! Thanks for your help debugging.
