### ISSUE TITLE
Support auth token for fetching repository informations

### ISSUE THREAD

**Issue by zekth** [Justintime50/homebrew-releaser#26]
The current action doesn't work with private repositories because of:
https://github.com/Justintime50/homebrew-releaser/blob/cccd49ea67b257c91d92365a93cd8a0e8f4f8b13/homebrew_releaser/app.py#L68

In the case of a private repository we need to be able to specify authentication prefix like:
```
curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/tarball/REF
```
see: https://docs.github.com/fr/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-tar

Would it be possible to have this in the future?

**Comment by Justintime50** [comment]
Hey @zekth, thanks for the great feature suggestion! This is definitely something we should add. I'll toss up a PR in the next couple days to tackle this.

**Comment by zekth** [comment]
> Hey @zekth, thanks for the great feature suggestion! This is definitely something we should add. I'll toss up a PR in the next couple days to tackle this.

We can basically reuse the commit token as a bearer token. That would work straight away

**Comment by Justintime50** [comment]
@zekth we'd want to use the repos token since the homebrew tap token already getting passed in via `github_token` may have scoped permissions to the tap and not the repo getting released

**Comment by Justintime50** [comment]
Actually I was thinking about this incorrectly, my big concern was that the tokens used would be scoped to the tap repo only but only recently (last few weeks/months) did GitHub start allowing for fine-grained tokens meaning the change you suggested should be backwards compatible. I left more details on the PR. Merging and releasing shortly.

**Comment by Justintime50** [comment]
You should be good to try this, either via the `v1` action or the more explicitly released `v0.15.0` action. Let me know if you run into any issues and thanks again for the feature suggestion!

**Comment by zekth** [comment]
Awesome!

**Comment by zekth** [comment]
@Justintime50 it seems like it fails at download the archive even if it's there see:
```console
2023-03-01 11:14:27,331 - INFO - Starting Homebrew Releaser...
2023-03-01 11:14:27,331 - DEBUG - All required environment variables are present.
2023-03-01 11:14:27,331 - INFO - Setting up git environment...
Cloning into 'homebrew-kong-internal'...
2023-03-01 11:14:28,097 - DEBUG - Git environment setup successfully.
2023-03-01 11:14:28,098 - INFO - Collecting data about REPO...
2023-03-01 11:14:28,382 - DEBUG - HTTP GET request made successfully to https://api.github.com/repos/ORG/REPO.
2023-03-01 11:14:28,635 - DEBUG - HTTP GET request made successfully to https://api.github.com/repos/ORG/REPO/tags.
2023-03-01 11:14:28,635 - INFO - Latest release (0.0.11) successfully identified!
2023-03-01 11:14:28,635 - INFO - Generating tar archive checksum(s)...
2023-03-01 11:14:29,214 - DEBUG - HTTP GET request made successfully to https://github.com/ORG/REPO/archive/0.0.11.tar.gz.
2023-03-01 11:14:29,251 - DEBUG - 0.0.11.tar.gz written successfully.
2023-03-01 11:14:29,290 - DEBUG - Checksum for 0.0.11.tar.gz generated successfully: cda35bbb757e875cad548a2e95ddcbcdf61a1dce952bac4eaee09cfd4c661a84
2023-03-01 11:14:29,290 - DEBUG - checksum.txt written successfully.
2023-03-01 11:14:29,854 - DEBUG - HTTP GET request made successfully to https://github.com/ORG/REPO/archive/0.0.11.zip.
2023-03-01 11:14:29,893 - DEBUG - 0.0.11.zip written successfully.
2023-03-01 11:14:29,929 - DEBUG - Checksum for 0.0.11.zip generated successfully: be0a12716fb06378b5041a888c2427a7a36d9dad58bcf5c8b71dcbac0d059fac
2023-03-01 11:14:29,929 - DEBUG - checksum.txt written successfully.
404 Client Error: Not Found for url: https://github.com/ORG/REPO/releases/download/0.0.11/REPO-0.0.11-darwin-amd64.tar.gz
```

**Comment by Justintime50** [comment]
I need to do a bit of research in addition to what you provided. That seems to mostly work to get us the archives in the action, there are some additional items needed once the formula actually gets generated since Homebrew out of the box won't let you install these archives from a private repo. This may take me a couple days but I'll chip away at it.

**Comment by zekth** [comment]
@Justintime50 we use this `GithubPrivateRepositoryDownloadStrategy`  as a lib in an internal homebrew in Kong: 
https://github.com/Homebrew/brew/pull/1763/files

example for the go-releaser of one lib
```yaml

brews:
  - tap:
      owner: Kong
      name: private-homebrew
      branch: main
    folder: Formula
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: lib/private_strategy
    homepage: ....
    description: ...
    install: |
      ....
```

**Comment by Justintime50** [comment]
Exactly! Was looking at `GitHubPrivateRepositoryReleaseDownloadStrategy`. Would you prefer this be passed in then explicitly by the user or generated automatically based on if the repo was private or not?

**Comment by zekth** [comment]
I'd expect the strategy to be a parameter because i think users might have other policies that they rely on. It's a niche use case i feel.

**Comment by Justintime50** [comment]
@zekth it appears users need to define `GitHubPrivateRepositoryReleaseDownloadStrategy` themselves? Or is this available from a Homebrew context somehow? It's saying it can't find that strategy for me. I found a PR where this got added to Brew but I'm unsure how to import/access it? Does every project have to reimplement that strategy themselves?

**Comment by zekth** [comment]
> @zekth it appears users need to define `GitHubPrivateRepositoryReleaseDownloadStrategy` themselves? Or is this available from a Homebrew context somehow? It's saying it can't find that strategy for me. I found a PR where this got added to Brew but I'm unsure how to import/access it? Does every project have to reimplement that strategy themselves?

It might have been added to core but so far I've seen people reimplementing it like we do also

**Comment by Justintime50** [comment]
I've been able to test this process end to end with a private repo and everything seems to be working as expected. I need to fix a small bug with the checksum generation that is off but should hopefully have this ready shortly.

**Comment by Justintime50** [comment]
Alright, this is merged and released. Feel free to give it another go, should work out this time!

**Comment by zekth** [comment]
Excellent it works! Thanks a ton!

**Comment by Justintime50** [comment]
Glad to hear! Thanks again for the request.
