### ISSUE TITLE
Add support for include section and resource blocks

### ISSUE THREAD

**Issue by Yarden-zamir** [Justintime50/homebrew-releaser#32]
Maybe I'm missing something but I have a python project with some python packages and I don't see a way to define the required `include Language::Python::Virtualenv` and or the resources, for example 
```
  resource "PyYAML" do
    url "https://pypi.python.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz"
    sha256 "592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab"
  end
```
Is there a way to do this that I'm missing?

**Comment by Yarden-zamir** [comment]
https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md#example-formula

**Comment by Justintime50** [comment]
Hey there, thanks for the feature request! This is not currently supported. I'll need to do a bit of research into this.

Will each of your python packages be in their own repo I assume? Seems like we need two things here, the ability to include the `include Language::Python::Virtualenv` line and point the url to pypi or another location other than github, is that correct? Is there anything else needed for this to work properly?

**Comment by Yarden-zamir** [comment]
Alternativley an advanced custom codeblock addition would also work

**Comment by Justintime50** [comment]
I assume then you'd need to automate how you get/populate the url and checksum in your custom codeblock? Could that be done easily via the GitHub Action yaml? I'm all for adding a custom codeblock section but fear it may be difficult to actually use in this flow unless you already have a solve for that?

**Comment by Justintime50** [comment]
I'm going to close this due to inactivity. Please feel free to reopen and respond if you'd like to continue the conversation!
