### ISSUE TITLE
custom codeblock

### ISSUE THREAD

**Issue by Yarden-zamir** [Justintime50/homebrew-releaser#33]
Alternativley an advanced custom codeblock addition would also work
so one might add
```yaml
custom_init: |
  include Language::Python::Virtualenv

  url "..."

  resource "six" do
    url "https://files.pythonhosted.org/packages/71/39/171f1c67cd00715f190ba0b100d606d440a28c93c7714febeca8b79af85e/six-1.16.0.tar.gz"
    sha256 "1e61c37477a1626458e36f7b1d82aa5c9b094fa4802892072e49de9c60c4c926"
  end

  resource "parsedatetime" do
    url "https://files.pythonhosted.org/packages/a8/20/cb587f6672dbe585d101f590c3871d16e7aec5a576a1694997a3777312ac/parsedatetime-2.6.tar.gz"
    sha256 "4cb368fbb18a0b7231f4d76119165451c8d2e35951455dfee97c62a87b04d455"
  end
```
and then add the `virtualenv_install_with_resources` to the regular install section as usual

_Originally posted by @Yarden-zamir in https://github.com/Justintime50/homebrew-releaser/issues/32#issuecomment-1476674722_

**Comment by Justintime50** [comment]
I'm going to close this due to inactivity. Please feel free to reopen and respond if you'd like to continue the conversation!
