### ISSUE TITLE
autogenerated_tar_checksum has no value

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/homebrew-releaser#34]
For the repo https://github.com/dotcomrow/vault-ops-keys, an error keeps occurring where the `autogenerated_tar_checksum` isn't getting filled for some reason. Initial debugging doesn't turn anything up as the repo and release are being retrieved from the API correctly (seemingly), a release is being created, and the formula previously used to generate correctly.

I attempted to recreate the issue myself with this repo and was uncessful.

![Screenshot 2023-03-21 at 8 40 04 AM](https://user-images.githubusercontent.com/52037738/226608749-82ea772e-1918-448e-ae26-8662c9bc0e88.png)

_Originally posted by @mephmanx in https://github.com/Justintime50/homebrew-releaser/issues/29#issuecomment-1477771012_

**Comment by mephmanx** [comment]
Im following this now, thank you.

**Comment by Justintime50** [comment]
I was able to patch this issue via https://github.com/Justintime50/homebrew-releaser/commit/29e2b843ad2a87954f9ef81affddc5e7fb208d5d. Let me know if you run into more issues!

**Comment by mephmanx** [comment]
just use latest?

**Comment by Justintime50** [comment]
Yeah v1 or v0.16.5

**Comment by mephmanx** [comment]
Latest worked!  Thank you so much!

**Comment by Justintime50** [comment]
That repo doesn't exist. If you try viewing it on GitHub you'll get a 404: https://github.com/magic/unicorns.

You need to provide valid parameters for the repo to be able to get cloned.

You should also know the way you setup your github action is in an eternal release loop: 
![Screen Shot 2023-03-23 at 1 56 58 PM](https://user-images.githubusercontent.com/39606064/227337046-74bdb6f7-cdd1-4a89-b1b6-bae279a0a2fc.png)

Because this action commits to your repo and you have it set to auto release on every commit, it will forever be releasing new versions unless you change your config to only trigger on a release that is manually cut or some other alternative.

**Comment by mephmanx** [comment]
argh

**Comment by mephmanx** [comment]
I converted to your action from another quickly as the previous action stopped working as well...  ill look lcoser and clean it.  thanks.

**Comment by mephmanx** [comment]
I converted to your action from another quickly as the previous action stopped working as well...  ill look lcoser and clean it.  thanks.
