### ISSUE TITLE
multiline install section

### ISSUE THREAD

**Issue by mephmanx** [Justintime50/homebrew-releaser#35]
is there a way to make this work:

# Custom install command for your formula.
          # Required - string
          install: |
            'bin.install "show-keys.sh" => "show-keys" \n prefix.install 'files''

**Comment by Justintime50** [comment]
Yeah you should be able to do this:

```
install: |
        bin.install "show-keys.sh" => "show-keys"
        prefix.install 'files'
```

Let me know if that works.

**Comment by mephmanx** [comment]
It shows up in the formula but looks like this and things arent happy about the missing tab...you have it without quotes though..let me try that.
<img width="860" alt="Screenshot 2023-04-01 at 5 06 38 PM" src="https://user-images.githubusercontent.com/52037738/229313994-46da651e-477e-411f-b4d4-be3ce143b216.png">

**Comment by Justintime50** [comment]
Yeah the pip `|` in yaml indicates to take everything after it as literal, eg: https://yaml-multiline.info/. You shouldn't need the quotes at that point. You may need to play with the indentation to get it all working but checking the yaml documentation should get you where you need to go.
