### ISSUE TITLE
Private repository + default asset downloads broken

### ISSUE THREAD

**Issue by unfrgivn** [Justintime50/homebrew-releaser#41]
It seems this was addressed about a year ago #26 but now something may have changed on GitHub's end. 

The scenario is a private repo release, without any explicit assets uploaded and trying to fetch the default tarball. I have confirmed if I upload the same tarball as a release asset with one of the architecture suffixes, e.g `-darwin-arm64.tar.gz` and enable that option, everything works as expected. It's when all four asset targets are false that the issue arises.

1. The default archive url is then set to the following which is inaccessible for private repos. 

```python
archive_base_url = f'https://github.com/{GITHUB_OWNER}/{GITHUB_REPO}/archive/refs/tags/{version}'
auto_generated_release_tar = f'{archive_base_url}.tar.gz'
```

2. The only way to fetch these with the new fine-grained access tokens is [documented here](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-tar) and the URL would instead be the `api.github.com` endpoint.

```python
auto_generated_release_tar = f'{GITHUB_BASE_URL}/repos/{GITHUB_OWNER}/{GITHUB_REPO}/tarball/{version}'
```

3. And then this yields an error (I redacted the variables)

```sh
415 Client Error: Unsupported Media Type for url: https://api.github.com/repos/{GITHUB_OWNER}/{GITHUB_REPO}/tarball/{version}
```

In order to resolve this I tried updated the GITHUB_HEADERS to match their API docs and allowing redirects, but the real issue is the streaming option.

Setting `stream=False` in the `def download_archive` method of `app.py` is the only change required for the download to complete and the rest of the tap generation to finish successfully. 

I am happy to make a PR for this, but making a change for this use-case would likely cause regression on public repos or other scenarios.

**Comment by Justintime50** [comment]
Thanks so much for your PR! It's merged and released under v0.18.2 or v1, whichever you prefer.
