### ISSUE TITLE
Quoted commits on tap repo?

### ISSUE THREAD

**Issue by unfrgivn** [Justintime50/homebrew-releaser#45]
I wanted to ask before just submitting a PR to customize or update. The commits that are pushed to the tap repo are wrapped in double quotes. Is this intentional? 

*git.py line 51*
`f'"Brew formula update for {repo_name} version {version}"'`

 
<img width="512" alt="commits" src="https://github.com/Justintime50/homebrew-releaser/assets/1675472/c9bc0f57-0a29-42a0-9929-af5cad03794c">

**Comment by Justintime50** [comment]
Nope! Probably there in error or from some long distant change and the nested double quotes could be done away with! Happy to accept that change.

**Comment by Justintime50** [comment]
I had some time, addressed in https://github.com/Justintime50/homebrew-releaser/commit/1b6b02527142f9a6a661bd519aacf272b47c99e7

Thanks for the callout!

**Comment by unfrgivn** [comment]
Turned it into a conventional commit, even better! Thanks
