### ISSUE TITLE
Invalid class name generated for formula name containing a number

### ISSUE THREAD

**Issue by cdzombak** [Justintime50/homebrew-releaser#47]
See: https://github.com/cdzombak/homebrew-oss/actions/runs/11241532954/job/31253290018#step:7:19

homebrew-releaser generated the formula for this tool. `brew test-bot` is reporting this error:

```
In formula file: /usr/local/Homebrew/Library/Taps/cdzombak/homebrew-oss/formula/mqtt2influxdb.rb
Expected to find class Mqtt2influxdb, but only found: Mqtt2Influxdb.
```

I guess Homebrew does not consider a numeral to be equivalent to a `_` and does not expect CamelCase to apply to the first letter after a numeral.

**Comment by Justintime50** [comment]
Problem line is here: https://github.com/Justintime50/homebrew-releaser/blob/250a4793ce3e1cda719a6d06dd4508f20582838e/homebrew_releaser/formula.py#L56

Essentially Python treats non-alphabetic characters as word boundaries meaning it is considering `Influxdb` a new word. Too bad Homebrew doesn't agree.

**Comment by cdzombak** [comment]
> Interesting, so it should have been `Mqtt2influxdb` instead of `Mqtt2Influxdb`?

Apparently, yes.

> Can we confirm that a 2 in the name is valid for formula?

I believe it is. There are a bunch of examples in the `homebrew-core` repo; one with an extremely similar name is `Hcl2json`: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/h/hcl2json.rb

> Too bad Homebrew doesn't agree.

I wish Homebrew would just live and let live. Alas.

> Problem line is here:
> 
> https://github.com/Justintime50/homebrew-releaser/blob/250a4793ce3e1cda719a6d06dd4508f20582838e/homebrew_releaser/formula.py#L56
> 
> Essentially Python treats non-alphabetic characters as word boundaries meaning it is considering `Influxdb` a new word.

In case it's helpful, the following code produces the expected result in all cases I've tested:

```python
#!/usr/bin/env python3

import re

def homebrewClassName(s):
    return re.sub(r'[-_. ]+', '', 
        re.sub(r"\d([A-Z])", lambda mo: mo.group(0).lower(), s.title())
    )

print(homebrewClassName("mqtt2influxdb")) # Mqtt2influxdb
print(homebrewClassName("macos-ups-mqtt-connector")) # MacosUpsMqttConnector: https://github.com/cdzombak/homebrew-oss/blob/main/formula/macos-ups-mqtt-connector.rb (note, failure on this build is due to the mqtt2influxdb file)
print(homebrewClassName("fooBarBazTool")) # Foobarbaztool (I don't have any Homebrew-packaged programs with this naming convention)
print(homebrewClassName("energybridge_to_influxdb")) # EnergybridgeToInfluxdb: https://github.com/cdzombak/homebrew-oss/blob/main/formula/energybridge_to_influxdb.rb
print(homebrewClassName("windowstack2")) # Windowstack2: https://github.com/cdzombak/homebrew-oss/blob/main/formula/windowstack2.rb
```

**Comment by cdzombak** [comment]
Thank you as always, @Justintime50!
