### ISSUE TITLE
Allow specifying tar URL

### ISSUE THREAD

**Issue by jmgilman** [Justintime50/homebrew-releaser#9]
Currently, the script assumes the end-user wants homebrew to download the tarball of the repo at the latest version. My CI pipeline already builds binaries for all major OS's and attaches them to a Github release. It would be much better to have homebrew download the compiled binary in my case and then just run a `bin install` command.

**Comment by Justintime50** [comment]
This is probably something we can incorporate here. Can you provide a link to one of your projects where you'd like to do this so I can see it in action?

To clarify, do you just have a single binary that you'd want to install, is it standalone or in a zip or tarball attached to the release?

**Comment by jmgilman** [comment]
You can see an example of the release workflow here: https://github.com/jmgilman/vaultssh/blob/master/.github/workflows/release.yml

That produces a release like this: https://github.com/jmgilman/vaultssh/releases/tag/v0.1.0

If the goal is to follow after `goreleaser`, I actually have a Go version of this binary that I've used `goreleaser` with and it produces the below formula:

```ruby
# This file was generated by GoReleaser. DO NOT EDIT.
class Vssh < Formula
  desc "A small CLI wrapper for authenticating with SSH keys from Hashicorp Vault"
  homepage "https://github.com/jmgilman/vssh"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jmgilman/vssh/releases/download/v0.1.2/vssh_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "07de706b33a2b9fc776bcf4c549e4a7e61acc493202125aa2141808f17ad915a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jmgilman/vssh/releases/download/v0.1.2/vssh_0.1.2_Linux_x86_64.tar.gz"
      sha256 "e6e77895da5b87debef8231463f65b490127ea815f9b6fc67d2ff155830d8197"
    end
  end

  def install
    bin.install "vssh"
  end
end
```

Notice how it differentiates the architecture and provides hardlinks to the different artifacts and then just uses `bin.install` to avoid building on the end user's machine. In my case, Rust compiling can be pretty intensive and takes upwards of five minutes on my Macbook Pro.

**Comment by Justintime50** [comment]
I see, so you're building your own tarballs?

So really, there's two requests here: 1) to support platform specific install targets and 2) to support a user provided tar url from the latest release (so that you could pass it into each install target)?

**Comment by jmgilman** [comment]
Potentially, yes. I suppose it primarily depends on the targeted use case of the action. With the default behavior of downloading the tarball of the repository is the underlying assumption that most users of the action will be installing shell scripts or files from other scripted languages? As far as I know, it's unusual for a Homebrew package to default to compiling on a user's machine - usually, the default behavior is downloading a precompiled binary and then an alternative method of compiling from source is also offered. 

So, the real question here is how does this action intend on supporting compiled binaries?

**Comment by Justintime50** [comment]
At the moment, I suppose the project does assume that there are ready to ship assets residing in the repo already (this has worked for my initial use case of simple shell scripts that don't really need any build process); however, I suppose that this is not ideal for actual binaries as the only option to use this action with the current behavior would be to keep copies of your binaries to distribute in the git repo which isn't ideal for various reasons.

With that being said, I'm open to keeping what I just mentioned as the fallback or default behavior with the ability of the user to overwrite this behavior. Do you have a vision for how you'd want to be using this action assuming it had this capability? Meaning, how best would you define which tarball to pull from in the workflow config? Would you have your release tarball always be named the same across various releases and versions and we could just go to the most recent release to grab the tarball and the user would provide the name of the tarball?

**Comment by jmgilman** [comment]
The way I'm currently solving this is with templates. A [workflow like this](https://github.com/jmgilman/vaultssh/blob/master/.github/workflows/brew.yml) in the source repository is responsible for building the formula. The last step dispatches to [this workflow](https://github.com/jmgilman/homebrew-apps/blob/master/.github/workflows/update.yml) which creates a PR with the compiled template.

Not ideal really, but it works in the meantime. As for a solution using what exists here - it's not unreasonable to assume a fairly static naming structure for the tarballs. The only thing that would change in the download URL would be the release version. The hardest part is building a working formula that can support more than one platform (i.e. Linux, Mac, M1 Mac). The `go-releaser` package manages it but I haven't looked into how they are doing it.

**Comment by Justintime50** [comment]
Ah gotcha, thanks for the added context! I'm a bit short on time at the moment to look into this in-depth. Feel free to continue adding thoughts here or take a crack at a PR that would solve this. I'll circle back around to this in the future and take another look.

**Comment by Justintime50** [comment]
I've circled back to this and done a bit of research on how GoReleaser does this. Basically they allow your to specify a "pattern" or "template" URL where it will inject the correct values based on the platform/OS etc when building the formula file. I'm doing a bit of preliminary work surrounding the checksum logic that will make introducing this new feature here easier. Once that's complete I'll work on a way to allow users to specify a tar URL - still need to do a bit of research but I think I know how we'll go about this here.

**Comment by Justintime50** [comment]
Did some more digging into how this occurs for GoReleaser and am still a bit confused at how they seem to infer on what needs to be built.

My proposal is to add a new yaml section of which OSs to build for (macOS, Linux, and Windows only for now), the list specified will have a separate OS target in the generated formula, and the binary URL names will need to follow a pattern (something like containing the OS name in the URL, etc). This allows the user to specify which of the 3 they want to include while keeping the fallback of the default URL.

Do you only need to differentiate between OSs for now? I don't necessarily want to dive into all the different hardware combinations at this point if it can be avoided.

**Comment by Justintime50** [comment]
I'm getting pretty close I believe to having this implemented. I'm running after an issue with `brew audit` on the generated formula, then I'll need to end to end test this and document it and it should be good to go. The beauty is this should keep the current behavior while extending the options users have to specify which OS/Archs they have binaries for. It will need to follow a specified pattern, but I'll make sure it's documented in the README.

**Comment by Justintime50** [comment]
@jmgilman this has been released! Thanks for your patience and sorry it took so long (hopefully this can still benefit you). You can now pass various new booleans in the workflow yaml:

```
          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
          target_linux_arm64: true
```

Doing so will have the workflow look for those tar archives on your most recent release. You'll need to follow the pattern detailed in the README for the URL; however, it should pretty much match the one you gave as an example above (you cannot at present specify a custom URL).

I'd highly encourage turning on debug mode and skipping the commit and maybe even running it locally (or running it dry on CI a couple times) prior to using the new matrix build targets to ensure the formula builds the way you are looking for. I did a bunch of end to end tests which seemed to get the right result along with a bunch of unit tests but would love any feedback you have in production. Best!
